CREATE TABLE IF NOT EXISTS cms_home_banner_config (
    id BIGINT NOT NULL AUTO_INCREMENT,
    config_key VARCHAR(32) NOT NULL,
    main_title VARCHAR(120) NOT NULL,
    sub_title VARCHAR(500) NULL,
    background_image_media_id BIGINT NULL,
    primary_enabled TINYINT NOT NULL DEFAULT 0,
    primary_text VARCHAR(32) NULL,
    primary_target_type VARCHAR(32) NULL,
    primary_route_path VARCHAR(255) NULL,
    primary_anchor_code VARCHAR(64) NULL,
    primary_external_url VARCHAR(500) NULL,
    primary_open_in_new_tab TINYINT NOT NULL DEFAULT 0,
    secondary_enabled TINYINT NOT NULL DEFAULT 0,
    secondary_text VARCHAR(32) NULL,
    secondary_target_type VARCHAR(32) NULL,
    secondary_route_path VARCHAR(255) NULL,
    secondary_anchor_code VARCHAR(64) NULL,
    secondary_external_url VARCHAR(500) NULL,
    secondary_open_in_new_tab TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    deleted_marker BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_cms_home_banner_config PRIMARY KEY (id),
    CONSTRAINT uk_cms_home_banner_config_key_deleted_marker UNIQUE (config_key, deleted_marker)
);

INSERT INTO cms_home_banner_config (
    config_key,
    main_title,
    sub_title,
    background_image_media_id,
    primary_enabled,
    primary_text,
    primary_target_type,
    primary_route_path,
    primary_anchor_code,
    primary_external_url,
    primary_open_in_new_tab,
    secondary_enabled,
    secondary_text,
    secondary_target_type,
    secondary_route_path,
    secondary_anchor_code,
    secondary_external_url,
    secondary_open_in_new_tab,
    version,
    created_by,
    updated_by,
    deleted_marker
)
SELECT
    'default',
    '',
    '',
    NULL,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    0,
    NULL,
    NULL,
    0
WHERE NOT EXISTS (
    SELECT 1 FROM cms_home_banner_config WHERE config_key = 'default' AND deleted_marker = 0
);
